language: node_js
node_js:
- '8.1'
script:
- npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: time.orbas.net
  region: ap-northeast-1
  local_dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: flash662/time-record
after_deploy:
  - pip install --user awscli
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"